// SPDX-License-Identifier: Unlicense
// Compile author-owned Markdown and inline LaTeX; no build dependency runs in the browser.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import MarkdownIt from 'markdown-it';
import temml from 'temml';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sourceDirectory=path.join(root,'docs/content/explorer');
const destination=path.join(root,'docs/assets/content.generated.js');
const equationDestination=path.join(root,'docs/assets/equations.generated.js');
const field=/\{\{([\p{L}][\p{L}\p{N}_]*)\}\}/gu;
const markdown=new MarkdownIt({html:false,typographer:false});
// A small Markdown extension handles only the delimiter. Temml owns TeX parsing.
markdown.inline.ruler.before('escape','inline_math',(state,silent)=>{
  if(state.src[state.pos]!=='$')return false;
  let end=state.pos+1;
  while((end=state.src.indexOf('$',end))!==-1&&state.src[end-1]==='\\')end++;
  if(end===-1||end===state.pos+1)return false;
  if(!silent){const token=state.push('inline_math','math',0);token.content=state.src.slice(state.pos+1,end);}
  state.pos=end+1;return true;
});
function math(tex,displayMode=false){
  // Two groups keep each value in an mrow. Adjacent mn placeholders would be
  // concatenated by Temml, losing the second one's binding attribute.
  const source=tex.replace(field,(_,name)=>`\\data{content-value=${name}}{{0}{}}`);
  const html=temml.renderToString(source,{displayMode,throwOnError:true,trust:context=>context.command==='\\data'});
  const expected=new Map();
  for(const [,kind,name]of source.matchAll(/\\data\{content-(value|result|copy)=([^{}]+)\}/gu)){
    const attribute=`data-content-${kind}="${markdown.utils.escapeHtml(name)}"`;
    expected.set(attribute,(expected.get(attribute)??0)+1);
  }
  for(const [attribute,count]of expected)if(html.split(attribute).length-1!==count)throw Error(`MathML lost a binding: ${attribute}`);
  return html;
}
markdown.renderer.rules.inline_math=(tokens,index)=>math(tokens[index].content);
const fence=markdown.renderer.rules.fence;
markdown.renderer.rules.fence=(tokens,index,options,environment,self)=>tokens[index].info.trim()==='math'
  ?math(tokens[index].content,true):fence(tokens,index,options,environment,self);

const content={};
for(const file of fs.readdirSync(sourceDirectory).filter(file=>file.endsWith('.md')&&file!=='equations.md').sort()){
  const [format,language]=file.split('.');
  if(!['binary32','binary64','symbols','common'].includes(format)||!['en','ja'].includes(language))throw Error(`Unexpected content file ${file}`);
  content[language]??={};
  const source=fs.readFileSync(path.join(sourceDirectory,file),'utf8').replace(/\r\n/g,'\n');
  for(const section of source.split(/^## /m).slice(1)){
    const newline=section.indexOf('\n'),key=section.slice(0,newline).trim();
    let body=section.slice(newline).replace(/^\n+|\n+$/g,'');
    const directive=/^@notation([^\n]*)\n\n/u.exec(body);
    const notation=directive?directive[1].trim().split(/\s+/u).filter(Boolean):null;
    if(directive)body=body.slice(directive[0].length);
    if(!/^[\p{L}\p{N}_.-]+$/u.test(key))throw Error(`Invalid content ID ${file}: ${key}`);
    const id=`${format}.${key}`;
    if(Object.hasOwn(content[language],id))throw Error(`Duplicate content ID ${language}: ${id}`);
    const html=markdown.render(body);
    // Outside math, substitution happens in escaped text, never HTML attributes.
    const slots=[...new Set([...body.matchAll(field)].map(match=>match[1]))].sort();
    content[language][id]={html,plain:body,slots,notation};
  }
}
// Binary64 uses a single bilingual model; its authoring IDs must agree exactly.
for(const language of ['en','ja'])for(const id of Object.keys(content[language])){
  if((id.startsWith('binary64.')||id.startsWith('symbols.')||id.startsWith('common.'))&&!Object.hasOwn(content[language==='en'?'ja':'en'],id))throw Error(`Missing translation for ${id}`);
  for(const name of content[language][id].notation??[]){
    const format=id.split('.')[0];
    if(!Object.keys(content[language]).some(key=>key===`symbols.${name}`||key===`symbols.${format}.${name}`||key.startsWith(`symbols.${format}.`)&&key.endsWith(`.${name}`)))throw Error(`Unknown notation ${name} in ${id}`);
  }
  if(id.startsWith('binary64.')||id.startsWith('common.')){
    const other=content[language==='en'?'ja':'en'][id];
    for(const property of ['slots','notation'])if(JSON.stringify(content[language][id][property])!==JSON.stringify(other[property]))throw Error(`Translation ${property} differs for ${id}`);
  }
}
const output='// SPDX-License-Identifier: Unlicense\n// Generated by npm run build:docs. Edit docs/content/explorer/*.md.\nexport const CONTENT = '+JSON.stringify(content,null,2)+';\n';
const equations={},symbols={};
const slot=/\\(value|result)\{([^{}]+)\}/gu;
function alignResults(tex,id){
  if(!/\\result\{/.test(tex))return tex;
  const block=/^\\begin\{aligned\}\n([\s\S]*?)\n\\end\{aligned\}$/u.exec(tex);
  if(!block)throw Error(`Evaluated results require an aligned block: ${id}`);
  const rows=block[1].split(/\\\\\s*\n/u).map(row=>{
    const columns=row.split('&').length;
    if(columns!==2&&columns!==4)throw Error(`Expected a formula pair or an explicit result pair in ${id}`);
    if(!row.includes('\\result{'))return columns===4?row:row+' & &';
    const result=/\\result\{[^{}]+\}\s*$/u.exec(row);
    if(!result)throw Error(`Place the evaluated result at the end of the row: ${id}`);
    // A directly evaluated expression has no separate symbolic RHS.
    if(columns===2&&row.slice(0,result.index).trimEnd().endsWith('&'))return row+' & &';
    return columns===4?row:row.slice(0,result.index)+' &\\quad&'+result[0];
  });
  return '\\begin{alignedat}{2}\n'+rows.join(' \\\\\n')+'\n\\end{alignedat}';
}
for(const section of fs.readFileSync(path.join(sourceDirectory,'equations.md'),'utf8').replace(/\r\n/g,'\n').split(/^## /m).slice(1)){
  const newline=section.indexOf('\n'),id=section.slice(0,newline).trim(),body=section.slice(newline);
  if(!/^[\p{L}\p{N}_.-]+$/u.test(id))throw Error(`Invalid equation ID: ${id}`);
  const fence=/^```math\n([\s\S]*?)\n```$/mu.exec(body);
  if(!fence)throw Error(`Missing math block in ${id}`);
  const values=[],results=[],labels=[];
  const tex=alignResults(fence[1],id).replace(slot,(_,kind,name)=>{
    (kind==='value'?values:results).push(name);
    return `\\data{content-${kind}=${name}}{${kind==='value'?'{0}{}':'=0'}}`;
  }).replace(/\\copy\{([\p{L}\p{N}_.-]+)\}/gu,(_,name)=>{
    for(const language of ['en','ja'])if(!content[language][name]||content[language][name].slots.length)throw Error(`Missing plain math label ${language}: ${name}`);
    labels.push(name);return `\\data{content-copy=${name}}{\\text{${content.en[name].plain}}}`;
  });
  const isSymbol=id.startsWith('symbol.');
  const html=math(tex,!isSymbol);
  if(isSymbol){
    const name=/^@name (.+)$/mu.exec(body)?.[1]??id.slice(7);
    if(Object.hasOwn(symbols,name))throw Error(`Duplicate symbol: ${name}`);
    symbols[name]=html;
  }else{
    if(Object.hasOwn(equations,id))throw Error(`Duplicate equation: ${id}`);
    equations[id]={html,values:[...new Set(values)],results:[...new Set(results)],labels:[...new Set(labels)]};
  }
}
const equationOutput='// SPDX-License-Identifier: Unlicense\n// Generated by npm run build:docs. Edit docs/content/explorer/equations.md.\nexport const EQUATIONS = '+JSON.stringify(equations,null,2)+';\nexport const SYMBOLS = '+JSON.stringify(symbols,null,2)+';\n';
if(process.argv.includes('--check')){
  for(const [file,expected]of [[destination,output],[equationDestination,equationOutput]])if(!fs.existsSync(file)||fs.readFileSync(file,'utf8')!==expected)throw Error('Explorer content is stale. Run npm run build:docs.');
  console.log('Explorer prose and equations are current.');
}else{
  fs.writeFileSync(destination,output);
  fs.writeFileSync(equationDestination,equationOutput);
  console.log(`Compiled ${Object.values(content).reduce((count,entries)=>count+Object.keys(entries).length,0)} content entries, ${Object.keys(equations).length} equations and ${Object.keys(symbols).length} symbols.`);
}
