#!/usr/bin/env python3
"""Export the maintained binary64 Fast and compact reconstruction tables."""
import argparse
import hashlib
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def render():
    source = (ROOT / "include/boundragon/detail/decimal_tables.h").read_text(encoding="utf-8")
    lines = ["// Generated by tools/generate_explorer64_tables.py; do not edit.",
             "// SPDX-License-Identifier: Unlicense",
             "// decimal_tables.h: SHA-256 of LF source " + hashlib.sha256(source.encode()).hexdigest(),
             "export const POW_MIN = -293, COMPACT_BASE = -303;"]
    for cpp, js, pairs, count in [("high_powers", "HIGH_POWERS", False, 618),
                           ("compact_major", "MAJOR", True, 23), ("compact_minor", "MINOR", False, 28),
                           ("exp_shifts", "SHIFTS", False, 2048)]:
        body = re.search(rf"{cpp}\[\]\s*=\s*\{{(.*?)\}};", source, re.S).group(1)
        values = re.findall(r"0x[0-9a-fA-F]+|\b\d+\b", body)
        if pairs:
            values = [f"[{values[i]}n, {values[i+1]}n]" for i in range(0, len(values), 2)]
        else:
            values = [v + ("n" if js != "SHIFTS" else "") for v in values]
        assert len(values) == count, (cpp, len(values), count)
        lines.append(f"export const {js} = [")
        for i in range(0, len(values), 4 if pairs else 8):
            lines.append("  " + ", ".join(values[i:i+(4 if pairs else 8)]) + ",")
        lines.append("];")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / "docs/assets/tables64.js"
    expected = render()
    if args.check:
        if not target.is_file() or target.read_text(encoding="utf-8") != expected:
            raise SystemExit("Binary64 explorer tables differ; regenerate")
        print("Binary64 explorer tables match maintained C++ caches")
    else:
        target.write_bytes(expected.encode())
        print(target)
