#!/usr/bin/env python3
"""Generate binary32's 77 exact normalized 64-bit decimal powers.

Only Python integer arithmetic is used.  --check compares the generated file
with the committed header instead of rewriting it.
"""
from __future__ import annotations

import argparse
from pathlib import Path

MIN_POWER, MAX_POWER = -32, 44
ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "include/boundragon/detail/binary32_cache.h"


def normalized_power(p: int) -> tuple[int, int]:
    numerator, denominator = (10**p, 1) if p >= 0 else (1, 10**-p)
    e = numerator.bit_length() - denominator.bit_length()
    if e >= 0:
        if numerator < (denominator << e):
            e -= 1
    elif (numerator << -e) < denominator:
        e -= 1
    shift = 63 - e
    if shift >= 0:
        numerator <<= shift
    else:
        denominator <<= -shift
    value = numerator // denominator
    assert 1 << 63 <= value < 1 << 64
    return value, e


def generated() -> str:
    powers = [normalized_power(p)[0] for p in range(MIN_POWER, MAX_POWER + 1)]
    text = """// SPDX-License-Identifier: Unlicense
// Generated by tools/generate_binary32_cache.py using exact integer arithmetic.
// Include inside namespace boundragon::detail after <cstdint>.
#pragma once
inline constexpr int binary32_pow_min = -32, binary32_pow_max = 44;
alignas(64) inline constexpr uint64_t binary32_powers[] = {
"""
    for i in range(0, len(powers), 4):
        text += "    " + ", ".join(f"UINT64_C(0x{v:016x})" for v in powers[i:i+4]) + ",\n"
    return text + "};\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    source = generated()
    if args.check:
        if OUTPUT.read_text() != source:
            raise SystemExit(f"FAIL: {OUTPUT} differs from the exact generated cache")
        print("PASS: all 77 binary32 powers match exact integer generation (616 bytes)")
    else:
        OUTPUT.write_text(source)
        print("Wrote 77 binary32 cached powers: 616 numeric bytes")


if __name__ == "__main__":
    main()
