#!/usr/bin/env python3
"""Export the maintained binary32 caches for the static algorithm explorer."""
import argparse
import hashlib
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def render():
    outputs = ["// Generated by tools/generate_explorer_tables.py; do not edit.",
               "// SPDX-License-Identifier: Unlicense"]
    for filename, declarations in [
        ("binary32_cache.h", [("binary32_powers", "POWERS", "UINT64_C", 77)]),
        ("binary32_fast_cache.h", [("binary32_fast_parameters", "PARAMETERS", "UINT64_C", 255),
                                   ("binary32_power_significands", "POWER_SIGS", "UINT32_C", 255)])]:
        path = ROOT / "include/boundragon/detail" / filename
        source = path.read_text(encoding="utf-8")
        digest = hashlib.sha256(source.encode()).hexdigest()
        outputs.append(f"// {filename}: SHA-256 of LF source {digest}")
        for cpp, js, macro, count in declarations:
            body = re.search(rf"{cpp}\[\]\s*=\s*\{{(.*?)\}};", source, re.S).group(1)
            values = re.findall(rf"{macro}\(([^)]+)\)", body)
            assert len(values) == count, (cpp, len(values))
            outputs.append(f"export const {js} = [")
            for i in range(0, len(values), 4):
                outputs.append("  " + ", ".join(v + "n" for v in values[i:i+4]) + ",")
            outputs.append("];")
    return "\n".join(outputs) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / "docs/assets/tables.js"
    expected = render()
    if args.check:
        if not target.is_file() or target.read_text(encoding="utf-8") != expected:
            raise SystemExit("Explorer tables differ: run tools/generate_explorer_tables.py")
        print("Explorer tables match maintained C++ caches")
    else:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(expected.encode())
        print(target)
