#!/usr/bin/env python3
"""Generate exact Q40 binary32 filter parameters and normal-power results."""
import argparse
from fractions import Fraction
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tests"))
from binary32_oracle import oracle

OUTPUT = ROOT / "include/boundragon/detail/binary32_fast_cache.h"
Q = 1 << 40


def generated():
    parameters, coefficients = [], []
    for raw in range(255):
        q = max(raw, 1) - 150
        k = q * 315653 >> 20
        alpha = Fraction(2**q) if q >= 0 else Fraction(1, 2**-q)
        ten = lambda e: Fraction(10**e) if e >= 0 else Fraction(1, 10**-e)
        assert ten(k) <= alpha < ten(k+1)
        p = -k - 1
        alpha *= 10**p if p >= 0 else Fraction(1, 10**-p)
        w = (alpha * Q).__floor__()
        sig, exp, sign = oracle(raw << 23)
        assert 0 <= exp + 45 < 128 and 0 <= k + 46 < 128
        assert sig < 100000000 and sign == 0
        parameters.append(w | ((exp + 45) << 48) | ((k + 46) << 56))
        coefficients.append(sig)
    source = """// SPDX-License-Identifier: Unlicense
// Generated by tools/generate_binary32_fast_cache.py using exact rationals.
// Low 40 bits: floor(2^q * 10^(-k-1) * 2^40).
// Byte 6: canonical power-of-two exponent +45; byte 7: coarse exponent +45.
// Entries 0 and 1 share subnormal spacing; entry 0's power result is signed zero.
"""
    for name, kind, values, formatter in (
        ("binary32_fast_parameters", "uint64_t", parameters, lambda v: f"UINT64_C(0x{v:016x})"),
        ("binary32_power_significands", "uint32_t", coefficients, lambda v: f"UINT32_C({v})")):
        source += f"alignas(64) inline constexpr {kind} {name}[] = {{\n"
        for i in range(0, len(values), 4):
            source += "    " + ", ".join(formatter(v) for v in values[i:i+4]) + ",\n"
        source += "};\n"
    return source


def main():
    if not __debug__:
        raise RuntimeError("Exact generation requires Python assertions")
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    source = generated()
    if args.check:
        if OUTPUT.read_text() != source:
            raise SystemExit("FAIL: binary32 fast tables differ from exact generation")
        print("PASS: 255 Q40 parameters and canonical power results (3060 numeric bytes)")
    else:
        OUTPUT.write_text(source)


if __name__ == "__main__":
    main()
