#!/usr/bin/env python3
"""Generate exact cached powers with Python integers; no FP approximation.
All exponents and all compact reconstructions are checked at generation time.
"""
import argparse
from pathlib import Path
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true', help='verify the committed header without rewriting it')
args = parser.parse_args()
MASK=(1<<64)-1
MIN,MAX=-293,324

def power(k, bits=128):
    # CacheGeneration.lean proves this bit-length/correction/rescale/floor
    # formula and its width/error bounds for every positive rational input.
    # The compact-anchor search below remains a separate certificate task.
    num,den=(10**k,1) if k>=0 else (1,10**-k)
    e=num.bit_length()-den.bit_length()
    if e>=0:
        if num < (den<<e): e-=1
    else:
        if (num<<-e) < den: e-=1
    shift=bits-1-e
    a,b=(num<<shift,den) if shift>=0 else (num,den<<-shift)
    return a//b, a%b != 0,e

pows=[power(k)[0] for k in range(MIN,MAX+1)]
# Dougall-style reconstruction with normalized small powers. The low-bit
# correction is unnecessary for the certified fallback rounding formulas.
STRIDE=28
BASE= -303   # starting anchor; includes pmin
NBASE=(MAX-BASE)//STRIDE+1
minor=[power(r,64)[0] for r in range(STRIDE)]
major=[]
for j in range(NBASE):
    k0=BASE+j*STRIDE
    floor,nonint,e=power(k0)
    for bias in (0,1,2):
        anchor=floor+bias
        cand=[]
        for r in range(STRIDE):
            k=k0+r
            if k<MIN or k>MAX: continue
            prod=anchor*minor[r]
            approx=prod>>(64 if (prod>>191) else 63)
            diff=approx-power(k)[0]
            cand.append((k,diff))
        if all(0<=d<=1 for k,d in cand):
            assert all(((power(k)[0]+d) >> 64) == (power(k)[0] >> 64) for k,d in cand)
            major.append(anchor)
            break
    else: raise RuntimeError(f'No 1-bit correction for {k0}')

def arr(name,typ,values,formatfn,perline=4):
    s=f'alignas(64) inline constexpr {typ} {name}[] = {{\n'
    for i in range(0,len(values),perline): s+='  '+', '.join(map(formatfn,values[i:i+perline]))+',\n'
    return s+'};\n'
hex64=lambda x:f'0x{x:016x}ULL'
u128fmt=lambda x:'{'+hex64(x>>64)+', '+hex64(x&MASK)+'}'
res='// SPDX-License-Identifier: Unlicense\n// Generated by generate_decimal_tables.py. Exact integer arithmetic.\n#pragma once\n'
res+=f'inline constexpr int pow_min={MIN}, pow_max={MAX}, compact_base={BASE};\n'
res+=arr('full_powers','Words',pows,u128fmt,2)
res+=arr('high_powers','uint64_t',[x>>64 for x in pows],hex64)
res+=arr('compact_major','Words',major,u128fmt,2)
res+=arr('compact_minor','uint64_t',minor,hex64)
shifts=[]
for raw in range(2048):
    q=max(1,raw)-1075
    k=(q*315653)>>20
    shift=q+(((-k-1)*217707)>>16)+10
    shifts.append(shift)
res+=arr('exp_shifts','uint8_t',shifts,str,32)
output = Path(__file__).resolve().parents[1] / 'include/boundragon/detail/decimal_tables.h'
if args.check:
    if output.read_text() != res:
        raise SystemExit('FAIL: decimal_tables.h differs from exact generated tables')
    print('PASS: committed decimal tables match exact generation')
else:
    output.write_text(res)
print('full entries:',len(pows),'power bytes:',len(pows)*16)
print('compact data bytes:',len(major)*16+len(minor)*8,'major',len(major))
print('high plus compact:',len(pows)*8+len(major)*16+len(minor)*8)
print('shift table:',len(shifts),'shift range',min(shifts),max(shifts))
